/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBlankRouteImport } from './routes/app/blank'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppDecksRouteImport } from './routes/app/decks'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as PresentIdRouteImport } from './routes/present.$id'
import { Route as AppDeckIdRouteImport } from './routes/app/deck.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBlankRoute = AppBlankRouteImport.update({
  id: '/app/blank',
  path: '/app/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/app/create',
  path: '/app/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDecksRoute = AppDecksRouteImport.update({
  id: '/app/decks',
  path: '/app/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/app/import',
  path: '/app/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/app/templates',
  path: '/app/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeckIdRoute = AppDeckIdRouteImport.update({
  id: '/app/deck/$id',
  path: '/app/deck/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/blank': typeof AppBlankRoute
  '/app/create': typeof AppCreateRoute
  '/app/decks': typeof AppDecksRoute
  '/app/import': typeof AppImportRoute
  '/app/templates': typeof AppTemplatesRoute
  '/present/$id': typeof PresentIdRoute
  '/app/': typeof AppIndexRoute
  '/app/deck/$id': typeof AppDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/blank': typeof AppBlankRoute
  '/app/create': typeof AppCreateRoute
  '/app/decks': typeof AppDecksRoute
  '/app/import': typeof AppImportRoute
  '/app/templates': typeof AppTemplatesRoute
  '/present/$id': typeof PresentIdRoute
  '/app': typeof AppIndexRoute
  '/app/deck/$id': typeof AppDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/blank': typeof AppBlankRoute
  '/app/create': typeof AppCreateRoute
  '/app/decks': typeof AppDecksRoute
  '/app/import': typeof AppImportRoute
  '/app/templates': typeof AppTemplatesRoute
  '/present/$id': typeof PresentIdRoute
  '/app/': typeof AppIndexRoute
  '/app/deck/$id': typeof AppDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/blank'
    | '/app/create'
    | '/app/decks'
    | '/app/import'
    | '/app/templates'
    | '/present/$id'
    | '/app/'
    | '/app/deck/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/blank'
    | '/app/create'
    | '/app/decks'
    | '/app/import'
    | '/app/templates'
    | '/present/$id'
    | '/app'
    | '/app/deck/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/blank'
    | '/app/create'
    | '/app/decks'
    | '/app/import'
    | '/app/templates'
    | '/present/$id'
    | '/app/'
    | '/app/deck/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppBlankRoute: typeof AppBlankRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDecksRoute: typeof AppDecksRoute
  AppImportRoute: typeof AppImportRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  PresentIdRoute: typeof PresentIdRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDeckIdRoute: typeof AppDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/blank': {
      id: '/app/blank'
      path: '/app/blank'
      fullPath: '/app/blank'
      preLoaderRoute: typeof AppBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create': {
      id: '/app/create'
      path: '/app/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/decks': {
      id: '/app/decks'
      path: '/app/decks'
      fullPath: '/app/decks'
      preLoaderRoute: typeof AppDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/import': {
      id: '/app/import'
      path: '/app/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/app/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deck/$id': {
      id: '/app/deck/$id'
      path: '/app/deck/$id'
      fullPath: '/app/deck/$id'
      preLoaderRoute: typeof AppDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppBlankRoute: AppBlankRoute,
  AppCreateRoute: AppCreateRoute,
  AppDecksRoute: AppDecksRoute,
  AppImportRoute: AppImportRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  PresentIdRoute: PresentIdRoute,
  AppIndexRoute: AppIndexRoute,
  AppDeckIdRoute: AppDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
